### ISSUE TITLE
Problem with get current language

### ISSUE THREAD

**Issue by serega404** [OLEGSHA/Progressia#2]
I get null from package `ru.windcorp.progressia.client.localization` in function `getLanguage()`

![idea64_2COHUbQYWV](https://user-images.githubusercontent.com/38862669/100129667-e363bf00-2e92-11eb-878f-66b5dab4fd35.png)

**Comment by OLEGSHA** [comment]
This is because `Localizer.setLanguage(String)` is never invoked ATM; it is the only method that changes `Localizer.language`. Therefore the issue is related to test code: once we get a proper startup procedure, the localization module will hopefully set its language early on. Nevertheless, Language Context Provider shouldn't assume the locale has been set when the game crashes.

**Comment by ExceptNullpointer** [comment]
Now it is "fixed"
